language: python

python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"

install:
  - pip install -r requirements_dev.txt --use-mirrors
  - git clone https://github.com/quantmind/pulsar.git
  - cd pulsar
  - python setup.py install
  - cd ..
  - sudo rm -rf pulsar
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server

script:
  - pep8 stdnet --exclude stdnet/apps/searchengine/processors
  - sudo rm -rf stdnet
  - python -m covrun

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
