name: release

on:
  push:
    branches:
      - deploy
    tags-ignore:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.QMBOT_GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: test version
        run: make test-version
      - name: build python bundle
        run: "make bundle${{ matrix.python-version }}"
      - name: release to pypi
        run: make release-pypi
      - name: release to github
        if: matrix.python-version == '3.8'
        run: make release-github
